Add friends likes
BerezinYaroslav/java-filmorate pull request #4
Opened 2023-03-01 21:02 UTC by YaroslavBerezin

2023-03-02 14:01 UTC, TomattmanYandex requested changes
Привет, хорошая работа но еще есть что поправить

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService service) {
лучше использовать аннотацию @RequiredArgsConstructor так если появятся еще зависимости то не надо будет дополнительно менять код, просто добавил переменную и все

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return service.addFilm(film);
Валидировать лучше на уровне контроллера

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film) throws ValidationException, IncorrectIdException {
лучше такие ошибки наследовать От RuntimeException 
от Exception обычно наследуют те, которые понятно как обработать если она упадет, или обязательно обработать

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film) throws ValidationException, IncorrectIdException {
а ошибки который унаследованы от RuntimeException не надо указывать в секции throws

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film likeFilm(@PathVariable Integer id,
почему бы не назвать первую переменную filmId сразу код станет понятнее

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getMostLikedFilms(@RequestParam(defaultValue = "10") Integer count) {
а пометить что параметр не обязательный

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
те же коменты что и в предыдущем файле

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
Throwable лучше не проверять, так как они включают в себя Error которые отвечают за ошибки виртуальной машины, и если это появится, то  тут уже ничего не поможет

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    @ExceptionHandler({IncorrectIdException.class, NullPointerException.class, IncorrectArgumentException.class})
NullPointer появляется во множестве мест, не только если что то не найдено, поэтому не стоит его добавлять в этот обработчик

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film likeFilm(Integer id, Integer userId) throws IncorrectIdException, IncorrectArgumentException {
тут все то же про блок throws

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectArgumentException.java
> +public class IncorrectArgumentException extends Exception {
почему бы не наследовать от runtimeException все равно прокидываем ошибку до самого конца

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
стоило бы проверить что такой пользователь вообще существует

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        int result = f0.getLikesIds().size() - (f1.getLikesIds().size());
return -1 * (f0.getLikesIds().size() - f1.getLikesIds().size())

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Тут все то же что и в классе выше

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          validate(film);
Валидировать лучше на уровне контроллера

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new IncorrectIdException("Film with this ID does not exist when updating");
а вот тут лучше создать какую ни будь свою ошибку, например например NotFoundException и пробрасывать ее
а вообще обычно хранилище возвращает либо null либо Optional.empty() а уже логика как это обрабатывать реализуется на сервисном уровне

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) {
уже выше комент на эту тему

2023-03-02 14:01 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
тут будут те же комментарии что и к хранилищу фильмов

2023-03-02 14:28 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return service.addFilm(film);
есть

2023-03-02 14:47 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
>          validate(film);
есть

2023-03-02 14:48 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film likeFilm(@PathVariable Integer id,
есть

2023-03-02 16:25 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService service) {
есть

2023-03-02 16:42 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film updateFilm(@RequestBody Film film) throws ValidationException, IncorrectIdException {
есть

2023-03-02 16:43 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getMostLikedFilms(@RequestParam(defaultValue = "10") Integer count) {
есть

2023-03-02 16:43 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
есть

2023-03-02 18:41 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new IncorrectIdException("Film with this ID does not exist when updating");
есть

2023-03-02 18:41 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (!films.containsKey(id)) {
есть

2023-03-02 18:41 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
есть

2023-03-02 18:47 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
есть

2023-03-02 18:47 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    @ExceptionHandler({IncorrectIdException.class, NullPointerException.class, IncorrectArgumentException.class})
есть

2023-03-02 18:47 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film likeFilm(Integer id, Integer userId) throws IncorrectIdException, IncorrectArgumentException {
есть

2023-03-02 18:47 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectArgumentException.java
> +public class IncorrectArgumentException extends Exception {
есть

2023-03-02 18:49 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
проверяется в getFilmById

2023-03-02 18:49 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        int result = f0.getLikesIds().size() - (f1.getLikesIds().size());
есть

2023-03-02 18:51 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
есть

2023-03-02 21:14 UTC, TomattmanYandex requested changes
Одно маленькое исправление осталось

2023-03-02 21:14 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
это фильм, а пользователь?

2023-03-03 12:59 UTC, TomattmanYandex requested changes
Все еще нету проверки что пользователь существует при добавлении лайка

2023-03-03 12:59 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikesIds().add(userId);
все еще нету проверки что юзер существует 
добавь зависимость от хранилища пользователей и проверь есть ли там пользователь

2023-03-03 13:07 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikesIds().add(userId);
есть

2023-03-03 13:08 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getFilmById(id);
понял

2023-03-03 13:25 UTC, TomattmanYandex approved these changes
Принято

2023-03-15 10:39 UTC, merged