ТЗ11 - Add database
BerezinYaroslav/java-filmorate pull request #6
Opened 2023-04-16 11:29 UTC by YaroslavBerezin

2023-04-16 23:21 UTC, TomattmanYandex requested changes
Привет тесты, но ты и сам знаешь
и надо оптимизировать запросы, очень много

2023-04-16 23:21 UTC, TomattmanYandex commented on Filmorate.png
схема базы вообще не правильная
1) у жанров должна быть отдельная таблица, а так как связь многие ко многим то должна быть отдельная связующая таблица
2) рейтинг - та же отдельная таблица но теперь связь один ко многим следовательно связующей таблица не надо
3) лайки - тоже отдельная таблица
4) друзья тоже но соединяет запись из - пользователей и пользователей

2023-04-16 23:21 UTC, TomattmanYandex commented on Filmorate.png
а если бы не посмотрел в файл создания базы, мог бы уже зарубить пулл реквест

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return this.filmService.updateFilm(film);
почему где то есть this а где то нету

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public Genre getGenre(@PathVariable Integer filmId) {
почему переменная называется filmId

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return likeStorage.getMostPopularFilm(count);
мы получаем фильмы почему метод в хранилище лайков

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (mpaStorage.getMpa(mpaId) != null) {
почему работает не так же как с жанрами? там было получше

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> optionalUser = userStorage.deleteUser(userId);
сложно и не совсем понятно

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendStorage.java
> +    List<User> getAllFriends(Integer userId);
лучше перенести в другой класс

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +    List<Film> getMostPopularFilm(Integer count);
тоже лучше в другой класс

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        if (filmRows.next()) {
можно удалить эту часть, так как мы не можем добавлять фильм сразу с лайками

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
а вот эту оставить, но лучше бы вынести в отдлеьный метод,и вызывать его тут

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
вот а если бы вынесено было в отдельный метод, то не было бы дублирования кода, был бы только вызов метода снова

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            Film film = getFilmById(filmRows.getInt("id")).get();
т.е. для того чтобы получить все фильмы, мы вместо одного запроса делаем N + 1 а так как там 6 запросов  то n * 6 + 1 
надо это переделать, для любого количества фильмов, должно быть максимум 3 запроса

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT * FROM \"film\" WHERE ID = ?", id);
некоторые запросы можно убрать, сделать  один запрос но с join

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            SqlRowSet filmRows1 = jdbcTemplate.queryForRowSet("SELECT * from \"film\" WHERE ID = ?",
второй запрос за теми же данными которые мы получили?

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    public Optional<Film> getFilmById(Integer id) {
тут тоже должно быть максимум 3 запроса

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/UserDbStorage.java
> +            User user = new User(
это можно вынести в отдельный метод, так как мы в нескольких местах собираем из строки базы обьект

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FriendDbStorage.java
> +            friends.add(userStorage.getUserById(id).get());
и снова сложность N вместо 1 надо исправлять

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/GenreDbStorage.java
> +            return Optional.of(new Genre(
снова место которое стоит вынести  в отдельный метод

2023-04-16 23:21 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/LikeDbStorage.java
> +            films.add(filmStorage.getFilmById(filmRows.getInt("id")).get());
и снова сложность, которую надо исправлять

2023-04-17 12:13 UTC, YaroslavBerezin commented on Filmorate.png
есть

2023-04-17 12:14 UTC, BerezinYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return this.filmService.updateFilm(film);
есть

2023-04-17 12:15 UTC, BerezinYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public Genre getGenre(@PathVariable Integer filmId) {
есть

2023-04-17 12:19 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return likeStorage.getMostPopularFilm(count);
есть

2023-04-17 12:23 UTC, BerezinYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +        if (mpaStorage.getMpa(mpaId) != null) {
есть

2023-04-17 12:25 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> optionalUser = userStorage.deleteUser(userId);
есть
опшионал нужен для того, чтобы определить, был ли такой юзер вообще

2023-04-17 12:29 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikeStorage.java
> +    List<Film> getMostPopularFilm(Integer count);
есть

2023-04-17 12:33 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            SqlRowSet filmRows1 = jdbcTemplate.queryForRowSet("SELECT * from \"film\" WHERE ID = ?",
есть

2023-04-17 12:57 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            Film film = getFilmById(filmRows.getInt("id")).get();
есть

2023-04-17 12:59 UTC, BerezinYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/FriendStorage.java
> +    List<User> getAllFriends(Integer userId);
есть

2023-04-17 13:00 UTC, BerezinYaroslav commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        if (filmRows.next()) {
есть

2023-04-17 17:11 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
есть, вынес метод получения жанров по айди фильма

2023-04-17 17:12 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
есть, выше

2023-04-17 18:21 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/GenreDbStorage.java
> +            return Optional.of(new Genre(
есть

2023-04-17 18:34 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    public Optional<Film> getFilmById(Integer id) {
есть

2023-04-17 18:41 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/UserDbStorage.java
> +            User user = new User(
есть

2023-04-17 18:41 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT * FROM \"film\" WHERE ID = ?", id);
сократил до 3

2023-04-17 20:44 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FriendDbStorage.java
> +            friends.add(userStorage.getUserById(id).get());
есть

2023-04-17 20:44 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/LikeDbStorage.java
> +            films.add(filmStorage.getFilmById(filmRows.getInt("id")).get());
есть

2023-04-18 13:20 UTC, TomattmanYandex requested changes
тесты еще надо доработать/переделать
по запросам в базу есть еще доработки тоже

2023-04-18 13:20 UTC, TomattmanYandex commented on README.md
> -# Java Filmorare Project
А почему все удалено?

2023-04-18 13:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
да но добавление фильмам жанров тоже можно вынести в отдельный метод, потому что тут такая логика, и при апдейте такая же логика, только там перед этим фильмы удалены

2023-04-18 13:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
что то типа
if (!film.getGenres().isEmpty()) {
addGenresToFIlm(film.getId(), film.getGenres())
}

2023-04-18 13:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +                SqlRowSet mpaRows = jdbcTemplate.queryForRowSet("SELECT * from \"mpa\" WHERE ID = ?",
MPA тут стоит получать через join 
тут можно сделалать тот же запрос что и в getAllFilms но добавить в него Where film_id = id

2023-04-18 13:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT * FROM \"film\" WHERE ID = ?", id);
Надо еще сократить 3 запроса это один на фильмы с мпа 
один на жанры, один на лайки, если лайки не добавляешь то два запроса

2023-04-18 13:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +public class DbTest {
тестируем отдельно каждый класс

2023-04-18 13:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +public class DbTest {
отдельный тест для каждого класса Storage

2023-04-18 13:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +    public void testGetGenreById_ExpectedGenreEquals() {
Выше нету модификатора доступа, тут есть, стоит сделать в одном стиле

2023-04-18 13:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +    void testGetAllMpa_ExpectedSize5() {
в именах тестовых методов не обязательно писать test достаточно имени тестируемого метода
но если очень хочется то лучше написать после имени тестируемого метода
пetAllMpaTest_итд

2023-04-18 13:20 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +public class DbTest {
и слишком малого тестовых методов, в идеале должен быть протестирован каждый метод, и на каждый метод по несколько случаев
в реальных проектах очень часто используются анализаторы кода, которые не пропускают сборку если покрытие нового кода тестами меньше определённого количества процентов, и чаще всего это число в районе 75

2023-04-18 13:38 UTC, YaroslavBerezin commented on README.md
> -# Java Filmorare Project
потому что из-за этого файла несовместимость у гита, я потом добавлю, после мержа

2023-04-18 16:48 UTC, YaroslavBerezin commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +    void testGetAllMpa_ExpectedSize5() {
есть

2023-04-18 16:50 UTC, YaroslavBerezin commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +    public void testGetGenreById_ExpectedGenreEquals() {
есть

2023-04-19 21:15 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
есть

2023-04-19 22:20 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet("SELECT * FROM \"film\" WHERE ID = ?", id);
есть

2023-04-19 22:22 UTC, YaroslavBerezin commented on src/test/java/ru/yandex/practicum/filmorate/DbTest.java
> +public class DbTest {
есть

2023-04-19 22:22 UTC, YaroslavBerezin commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +                SqlRowSet mpaRows = jdbcTemplate.queryForRowSet("SELECT * from \"mpa\" WHERE ID = ?",
есть

2023-04-19 23:40 UTC, YaroslavBerezin commented
Не пугайся, что много пушей, боролся с тестами: тесты юзера не в какую не проходили через гитхабовское тестирование, но по итогу получилось. Недочеты прошлые исправил.

2023-04-20 12:35 UTC, TomattmanYandex approved these changes
Принято, хотя конечно хотелось бы побольше тестов

2023-04-20 20:40 UTC, merged